---
title: "Maize_B73_ear_tip_IM-SPM_Slingshot_Github"

## Load all packages
```{r}
library(tidyverse)
library(slingshot)
library(Seurat)
library(tradeSeq)
library(S4Vectors)
library(SingleCellExperiment)
library(BUSpaRse)
library(tidymodels)
library(scales)
library(viridis)
library(Matrix)


```

## subcluster IM and SPM to run slingshot trajectory. 

```{r}

## IM use the original scale 

IM <- subset(B73.tip, idents = c(1, 3, 4))



IM.oriscale <- RunUMAP(IM, reduction = "pca", dims = 1:30) ## Use default 30

# Visualization

DimPlot(IM.oriscale, reduction = "umap", label = TRUE, pt.size = 1)

DimPlot(IM.oriscale, reduction = "umap", group.by = "subcluster6", pt.size = 1, label = TRUE, )


# Slingshot
# https://github.com/kstreet13/slingshot/issues/105

sdsIM.ori <- slingshot(Embeddings(IM.oriscale, "umap"), clusterLabels = IM.oriscale$subcluster6,
start.clus = 3, end.clus = c("1","4"), stretch = 0)

sdsIM.ori

## Unfortunately, slingshot does not natively support ggplot2. So this is a function that assigns colors to each cell in base R graphics.
## https://bustools.github.io/BUS_notebooks_R/slingshot.html#slingshot
## https://bustools.github.io/BUS_notebooks_R/slingshot.html#trajectory_inference

cell_pal <- function(cell_vars, pal_fun,...) {
  if (is.numeric(cell_vars)) {
    pal <- pal_fun(100, ...)
    return(pal[cut(cell_vars, breaks = 100)])
  } else {
    categories <- sort(unique(cell_vars))
    pal <- setNames(pal_fun(length(categories), ...), categories)
    return(pal[cell_vars])
  }
}



cell_colors_clust <- cell_pal(IM.oriscale$subcluster6, hue_pal()) 

plot(reducedDim(sdsIM.ori), col = cell_colors_clust, pch = 16, cex = 1)

lines(sdsIM.ori, lwd = 2, type = 'c', col = 'black') ## make sure type = 'c' which is the curve. 
lines(sdsIM.ori, lwd = 2, type = 'lineage', col = 'black') ## make sure type = 'c' which is the curve.


## Plot pseudotime for gene of interest. 

exp<-GetAssayData(IM.ori, slot = "data")

plotGenePseudotime(sdsIM.ori, "GRMZM2G372364", exp ) ## plot gene of interest one at a time for each lineages

plotGenePseudotime(sdsIM.ori, "GRMZM2G372364", col = cell_colors_clust, exp ) ## plot gene of interest one at a time for each lineages


## Which cells are in which lineage? Here we plot the pseudotime values for each lineage.


### curve
nc <- 3

pt <- slingPseudotime(sdsIM.ori)

nms <- colnames(pt)

nr <- ceiling(length(nms)/nc)

pal <- viridis(100, end = 0.95)

par(mfrow = c(nr, nc))

for (i in nms) {
  colors <- pal[cut(pt[,i], breaks = 100)]
  plot(reducedDim(sdsIM.ori), col = colors, pch = 16, cex = 1, main = i)
  lines(sdsIM.ori, lwd = 2, col = 'black', type = 'c')
}



#### lineage
nc <- 3

pt <- slingPseudotime(sdsIM.ori)

nms <- colnames(pt)

nr <- ceiling(length(nms)/nc)

pal <- viridis(100, end = 0.95)

par(mfrow = c(nr, nc))

for (i in nms) {
  colors <- pal[cut(pt[,i], breaks = 100)]
  plot(reducedDim(sdsIM.ori), col = colors, pch = 16, cex = 1, main = i)
  lines(sdsIM.ori, lwd = 2, col = 'black', type = 'lineage')
}

```





```{r}

## subcluster SPM to run slingshot trajectory. 

SPM.ori.scale <- subset(B73.tip, idents = c(5, 6, 12, 14))


SPM.ori.scale <- RunUMAP(SPM.ori.scale, reduction = "pca", dims = 1:30) ## Use default 30, or change the PC number based on above Elbow plot: quantitative approach

# Visualization

DimPlot(SPM.ori.scale, reduction = "umap", label = TRUE, pt.size = 1)

DimPlot(SPM.ori.scale, reduction = "umap", group.by = "subcluster6", pt.size = 1, label = TRUE)


# Slingshot
# https://github.com/kstreet13/slingshot/issues/105

sdsSPM.ori <- slingshot(Embeddings(SPM.ori.scale, "umap"), clusterLabels = SPM.ori.scale$subcluster6,
start.clus = 5, end.clus = c("6_0","6_1","12","14"), stretch = 0)

sdsSPM.ori

## Unfortunately, slingshot does not natively support ggplot2. So this is a function that assigns colors to each cell in base R graphics.
## https://bustools.github.io/BUS_notebooks_R/slingshot.html#slingshot
## https://bustools.github.io/BUS_notebooks_R/slingshot.html#trajectory_inference


cell_pal <- function(cell_vars, pal_fun,...) {
  if (is.numeric(cell_vars)) {
    pal <- pal_fun(100, ...)
    return(pal[cut(cell_vars, breaks = 100)])
  } else {
    categories <- sort(unique(cell_vars))
    pal <- setNames(pal_fun(length(categories), ...), categories)
    return(pal[cell_vars])
  }
}



cell_colors_clust <- cell_pal(SPM.ori.scale$subcluster6, hue_pal()) 

plot(reducedDim(sdsSPM.ori), col = cell_colors_clust, pch = 16, cex = 1)

lines(sdsSPM.ori, lwd = 2, type = 'c', col = 'black') ## make sure type = 'c' which is the curve. 
lines(sdsSPM.ori, lwd = 2, type = 'lineage', col = 'black') ## make sure type = 'c' which is the curve.

## Plot pseudotime for gene of interest. 

DefaultAssay(SPM.ori.scale) <- "RNA"

exp<-GetAssayData(SPM.ori.scale, slot = "data")

plotGenePseudotime(sdsSPM.ori, "GRMZM2G372364", exp ) ## plot gene of interest one at a time for each lineages

plotGenePseudotime(sdsSPM.ori, "GRMZM2G372364", col = cell_colors_clust, exp ) ## plot gene of interest one at a time for each lineages


## Which cells are in which lineage? Here we plot the pseudotime values for each lineage.


## curve
nc <- 3

pt <- slingPseudotime(sdsSPM.ori)

nms <- colnames(pt)

nr <- ceiling(length(nms)/nc)

pal <- viridis(100, end = 0.95)

par(mfrow = c(nr, nc))

for (i in nms) {
  colors <- pal[cut(pt[,i], breaks = 100)]
  plot(reducedDim(sdsSPM.ori), col = colors, pch = 16, cex = 1, main = i)
  lines(sdsSPM.ori, lwd = 2, col = 'black', type = 'c')
}


## lineage
nc <- 3

pt <- slingPseudotime(sdsSPM.ori)

nms <- colnames(pt)

nr <- ceiling(length(nms)/nc)

pal <- viridis(100, end = 0.95)

par(mfrow = c(nr, nc))

for (i in nms) {
  colors <- pal[cut(pt[,i], breaks = 100)]
  plot(reducedDim(sdsSPM.ori), col = colors, pch = 16, cex = 1, main = i)
  lines(sdsSPM.ori, lwd = 2, col = 'black', type = 'lineage')
}


```

