---
title: "xu16_19_29_32_vs_34_35"
output: html_document
---

## Load all packages
```{r}

library("rlang")
library("Seurat");
library("sctransform");
library("dplyr");
library("RColorBrewer");
library("ggthemes");
library("ggplot2");
library("cowplot");
library("data.table");
library("scales")


```


## Set up Seurat object
```{r}
## Find the origial CR path

setwd("C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu16_2017_cus_CR310_S150_L151")

setwd("C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu19_2017_cus_CR310_S150_L151")

setwd("C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu29_B73_tip")

setwd("C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu32_B73_tip")

setwd("C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu34_bif3")

setwd("C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu35_bif3")



## Read in the feature-barcode matrices generated by the cellranger pipeline.

memory.limit(size=50000000)

samples=c("xu16","xu19","xu29","xu32", "xu34", "xu35")

data.10x = list()

data.10x[[1]] <- Read10X(data.dir = "C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu16_2017_cus_CR310_S150_L151/raw_feature_bc_matrix");

data.10x[[2]] <- Read10X(data.dir = "C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu19_2017_cus_CR310_S150_L151/raw_feature_bc_matrix");

data.10x[[3]] <- Read10X(data.dir = "C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu29_B73_tip/raw_feature_bc_matrix");

data.10x[[4]] <- Read10X(data.dir = "C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu32_B73_tip/raw_feature_bc_matrix");

data.10x[[5]] <- Read10X(data.dir = "C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu34_bif3/raw_feature_bc_matrix");

data.10x[[6]] <- Read10X(data.dir = "C:/Users/Xiaosa Xu/Desktop/Seurat_2020/xu35_bif3/raw_feature_bc_matrix");


### 
setwd("C:/Users/Xiaosa Xu/Desktop/SC Stem Cell Manuscript/Seurat_sc_datasets/7_5_B73_ear_tip_vs_bif3_rerun")

## Convert each feature-barcode matrix to a Seurat object.

B73vsBif3.list = list(); # First create an empty list to hold the Seurat objects

B73vsBif3.list[[1]] = CreateSeuratObject(counts = data.10x[[1]], min.cells=3, min.features=200, project=samples[1]);

B73vsBif3.list[[1]][["DataSet"]] = samples[1];


B73vsBif3.list[[2]] = CreateSeuratObject(counts = data.10x[[2]], min.cells=3, min.features=200, project=samples[2]);

B73vsBif3.list[[2]][["DataSet"]] = samples[2];


B73vsBif3.list[[3]] = CreateSeuratObject(counts = data.10x[[3]], min.cells=3, min.features=200, project=samples[3]);

B73vsBif3.list[[3]][["DataSet"]] = samples[3];


B73vsBif3.list[[4]] = CreateSeuratObject(counts = data.10x[[4]], min.cells=3, min.features=200, project=samples[4]);

B73vsBif3.list[[4]][["DataSet"]] = samples[4];


B73vsBif3.list[[5]] = CreateSeuratObject(counts = data.10x[[5]], min.cells=3, min.features=200, project=samples[5]);

B73vsBif3.list[[5]][["DataSet"]] = samples[5];


B73vsBif3.list[[6]] = CreateSeuratObject(counts = data.10x[[6]], min.cells=3, min.features=200, project=samples[6]);

B73vsBif3.list[[6]][["DataSet"]] = samples[6];



## Optional, remove the raw data to save space:

rm(data.10x);


### Subset each library before merge or integrate


B73vsBif3.list[[1]] <- subset(B73vsBif3.list[[1]], subset = nCount_RNA > 5000 & nFeature_RNA > 1000 & nCount_RNA < 150000 & nFeature_RNA < 15000)

B73vsBif3.list[[2]] <- subset(B73vsBif3.list[[2]], subset = nCount_RNA > 5000 & nFeature_RNA > 1000 & nCount_RNA < 150000 & nFeature_RNA < 15000)

B73vsBif3.list[[3]] <- subset(B73vsBif3.list[[3]], subset = nCount_RNA > 5000 & nFeature_RNA > 1000 & nCount_RNA < 150000 & nFeature_RNA < 15000)

B73vsBif3.list[[4]] <- subset(B73vsBif3.list[[4]], subset = nCount_RNA > 5000 & nFeature_RNA > 1000 & nCount_RNA < 150000 & nFeature_RNA < 15000)

B73vsBif3.list[[5]] <- subset(B73vsBif3.list[[5]], subset = nCount_RNA > 5000 & nFeature_RNA > 1000 & nCount_RNA < 150000 & nFeature_RNA < 15000)

B73vsBif3.list[[6]] <- subset(B73vsBif3.list[[6]], subset = nCount_RNA > 5000 & nFeature_RNA > 1000 & nCount_RNA < 150000 & nFeature_RNA < 15000)


##

B73vsBif3.list[[1]]@meta.data$source <- "B73"
B73vsBif3.list[[2]]@meta.data$source <- "B73"
B73vsBif3.list[[3]]@meta.data$source <- "B73"
B73vsBif3.list[[4]]@meta.data$source <- "B73"

B73vsBif3.list[[5]]@meta.data$source <- "Bif3"
B73vsBif3.list[[6]]@meta.data$source <- "Bif3"




## logNormalize

B73vsBif3.list[[1]]<- NormalizeData(B73vsBif3.list[[1]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.list[[2]]<- NormalizeData(B73vsBif3.list[[2]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.list[[3]]<- NormalizeData(B73vsBif3.list[[3]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.list[[4]]<- NormalizeData(B73vsBif3.list[[4]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.list[[5]]<- NormalizeData(B73vsBif3.list[[5]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.list[[6]]<- NormalizeData(B73vsBif3.list[[6]], normalization.method = "LogNormalize", scale.factor = 10000)

## Find variables


B73vsBif3.list[[1]]<- FindVariableFeatures(B73vsBif3.list[[1]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.list[[2]]<- FindVariableFeatures(B73vsBif3.list[[2]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.list[[3]]<- FindVariableFeatures(B73vsBif3.list[[3]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.list[[4]]<- FindVariableFeatures(B73vsBif3.list[[4]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.list[[5]]<- FindVariableFeatures(B73vsBif3.list[[5]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.list[[6]]<- FindVariableFeatures(B73vsBif3.list[[6]], selection.method = "vst", nfeatures = 2000)

# select features that are repeatedly variable across datasets for integration


features <- SelectIntegrationFeatures(object.list = B73vsBif3.list)

# find anchors

anchors <- FindIntegrationAnchors(object.list = B73vsBif3.list, anchor.features = features)


# Integrate data
# this command creates an 'integrated' data assay

B73vsBif3.individual.int <- IntegrateData(anchorset = anchors)

# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay

DefaultAssay(B73vsBif3.individual.int)<-"integrated"


# Run the standard workflow for visualization and clustering
B73vsBif3.individual.int <- ScaleData(B73vsBif3.individual.int, verbose = FALSE)
B73vsBif3.individual.int <- RunPCA(B73vsBif3.individual.int, npcs = 30, verbose = FALSE)


```



```{r}
## Determine the ‘dimensionality’ of the dataset

ElbowPlot(B73vsBif3.individual.int, ndims = 40)

## Elbow plot: quantitative approach
## https://hbctraining.github.io/scRNA-seq/lessons/elbow_plot_metric.html

# Determine percent of variation associated with each PC
pct <- B73vsBif3.individual.int[["pca"]]@stdev / sum(B73vsBif3.individual.int[["pca"]]@stdev) * 100

# Calculate cumulative percents for each PC
cumu <- cumsum(pct)

# Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
co1 <- which(cumu > 90 & pct < 5)[1]

co1


# Determine the difference between variation of PC and subsequent PC
co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1

# last point where change of % of variation is more than 0.1%.
co2


# Minimum of the two calculation
pcs <- min(co1, co2)

pcs


```



```{r}
B73vsBif3.individual.int <- RunUMAP(B73vsBif3.individual.int, reduction = "pca", dims = 1:19) ## Use the PC number based on above Elbow plot: quantitative approach

B73vsBif3.individual.int <- FindNeighbors(B73vsBif3.individual.int, reduction = "pca", dims = 1:19)

B73vsBif3.individual.int <- FindClusters(B73vsBif3.individual.int, resolution = 0.85)

# Visualization

DimPlot(B73vsBif3.individual.int, reduction = "umap", label = TRUE, pt.size = 1)
DimPlot(B73vsBif3.individual.int, reduction = "umap", group.by = "orig.ident")

## two plots next to each other 

p1 <- DimPlot(B73vsBif3.individual.int, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(B73vsBif3.individual.int, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2

### split the UMAPs by samples 

DimPlot(B73vsBif3.individual.int, reduction = "umap", split.by = "orig.ident", pt.size = 1)


### group the UMAPs by samples. 

DimPlot(B73vsBif3.individual.int, reduction = "umap", group.by = "orig.ident", pt.size = 1)

```

```{r}
## Remove cluster 6 with very low UMI (dead cells)

B73vsBif3.individual.int_remove_dead <- subset(B73vsBif3.individual.int, idents = 6, invert = TRUE)

DimPlot(B73vsBif3.individual.int_remove_dead, reduction = "umap", label = TRUE, pt.size = 1)

### split the integrated object to re-normalize and process

B73vsBif3.rmdead.list <- SplitObject(B73vsBif3.individual.int_remove_dead, split.by = "orig.ident")

B73vsBif3.rmdead.list

```


```{r}

## need to set RNA assay before normalization and processing 

DefaultAssay(B73vsBif3.rmdead.list[[1]]) <- "RNA"
DefaultAssay(B73vsBif3.rmdead.list[[2]]) <- "RNA"
DefaultAssay(B73vsBif3.rmdead.list[[3]]) <- "RNA"
DefaultAssay(B73vsBif3.rmdead.list[[4]]) <- "RNA"
DefaultAssay(B73vsBif3.rmdead.list[[5]]) <- "RNA"
DefaultAssay(B73vsBif3.rmdead.list[[6]]) <- "RNA"



## logNormalize

B73vsBif3.rmdead.list[[1]]<- NormalizeData(B73vsBif3.rmdead.list[[1]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.rmdead.list[[2]]<- NormalizeData(B73vsBif3.rmdead.list[[2]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.rmdead.list[[3]]<- NormalizeData(B73vsBif3.rmdead.list[[3]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.rmdead.list[[4]]<- NormalizeData(B73vsBif3.rmdead.list[[4]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.rmdead.list[[5]]<- NormalizeData(B73vsBif3.rmdead.list[[5]], normalization.method = "LogNormalize", scale.factor = 10000)

B73vsBif3.rmdead.list[[6]]<- NormalizeData(B73vsBif3.rmdead.list[[6]], normalization.method = "LogNormalize", scale.factor = 10000)


##Find variables


B73vsBif3.rmdead.list[[1]]<- FindVariableFeatures(B73vsBif3.rmdead.list[[1]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.rmdead.list[[2]]<- FindVariableFeatures(B73vsBif3.rmdead.list[[2]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.rmdead.list[[3]]<- FindVariableFeatures(B73vsBif3.rmdead.list[[3]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.rmdead.list[[4]]<- FindVariableFeatures(B73vsBif3.rmdead.list[[4]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.rmdead.list[[5]]<- FindVariableFeatures(B73vsBif3.rmdead.list[[5]], selection.method = "vst", nfeatures = 2000)

B73vsBif3.rmdead.list[[6]]<- FindVariableFeatures(B73vsBif3.rmdead.list[[6]], selection.method = "vst", nfeatures = 2000)



# select features that are repeatedly variable across datasets for integration


features <- SelectIntegrationFeatures(object.list = B73vsBif3.rmdead.list)

# find anchors

anchors <- FindIntegrationAnchors(object.list = B73vsBif3.rmdead.list, anchor.features = features)


# Integrate data
# this command creates an 'integrated' data assay

B73vsBif3.individual.rmdead.int <- IntegrateData(anchorset = anchors)

DefaultAssay(B73vsBif3.individual.rmdead.int)<-"integrated"


# Run the standard workflow for visualization and clustering
B73vsBif3.individual.rmdead.int <- ScaleData(B73vsBif3.individual.rmdead.int, verbose = FALSE)
B73vsBif3.individual.rmdead.int <- RunPCA(B73vsBif3.individual.rmdead.int, npcs = 30, verbose = FALSE)


```



```{r}
## Determine the ‘dimensionality’ of the dataset

ElbowPlot(B73vsBif3.individual.rmdead.int, ndims = 40)

## Elbow plot: quantitative approach
## https://hbctraining.github.io/scRNA-seq/lessons/elbow_plot_metric.html

# Determine percent of variation associated with each PC
pct <- B73vsBif3.individual.rmdead.int[["pca"]]@stdev / sum(B73vsBif3.individual.rmdead.int[["pca"]]@stdev) * 100

# Calculate cumulative percents for each PC
cumu <- cumsum(pct)

# Determine which PC exhibits cumulative percent greater than 90% and % variation associated with the PC as less than 5
co1 <- which(cumu > 90 & pct < 5)[1]

co1

# Determine the difference between variation of PC and subsequent PC
co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1

# last point where change of % of variation is more than 0.1%.
co2

# Minimum of the two calculation
pcs <- min(co1, co2)

pcs

```



```{r}
B73vsBif3.individual.rmdead.int <- RunUMAP(B73vsBif3.individual.rmdead.int, reduction = "pca", dims = 1:24) ## Use PC number based on above Elbow plot: quantitative approach

B73vsBif3.individual.rmdead.int <- FindNeighbors(B73vsBif3.individual.rmdead.int, reduction = "pca", dims = 1:24)

B73vsBif3.individual.rmdead.int <- FindClusters(B73vsBif3.individual.rmdead.int, resolution = 0.85)

# Visualization

DimPlot(B73vsBif3.individual.rmdead.int, reduction = "umap", label = TRUE, pt.size = 1)

DimPlot(B73vsBif3.individual.rmdead.int, reduction = "umap", group.by = "orig.ident")

## two plots next to each other 

p1 <- DimPlot(B73vsBif3.individual.rmdead.int, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(B73vsBif3.individual.rmdead.int, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2

### split the UMAPs by samples 

DimPlot(B73vsBif3.individual.rmdead.int, reduction = "umap", split.by = "orig.ident", pt.size = 1)


### group the UMAPs by samples. 

DimPlot(B73vsBif3.individual.rmdead.int, reduction = "umap", group.by = "orig.ident", pt.size = 1)

```


```{r}
## Prepare Subcluster2 by assigning graph.name="mygraph"

##next run UMAP

DefaultAssay(B73vsBif3.individual.rmdead.int)<-"integrated"

B73vsBif3.individual.rmdead.int.subcluster <- RunUMAP(B73vsBif3.individual.rmdead.int, reduction = "pca", dims = 1:24)

B73vsBif3.individual.rmdead.int.subcluster <- FindNeighbors(B73vsBif3.individual.rmdead.int.subcluster, graph.name= "mygraph", dims = 1:24)

B73vsBif3.individual.rmdead.int.subcluster <- FindClusters(B73vsBif3.individual.rmdead.int.subcluster, graph.name = "mygraph", resolution = 0.9)


DimPlot(B73vsBif3.individual.rmdead.int.subcluster, reduction = "umap", label = TRUE, repel = TRUE, pt.size = 1, label.size = 10)

```


```{r}
### subcluster cluster
B73vsBif3.individual.rmdead.int.subcluster2 <- FindSubCluster(B73vsBif3.individual.rmdead.int.subcluster, "2", "mygraph", subcluster.name = "subcluster2",  resolution = 0.2, algorithm = 1)

## Plot the sub-cluster 

DimPlot(B73vsBif3.individual.rmdead.int.subcluster2, reduction = "umap", group.by = "subcluster2", label = TRUE, label.size = 10, pt.size = 1)

```



```{r}
## transfer subcluster2 identity as active identity 

Idents(B73vsBif3.individual.rmdead.int.subcluster2) <- "subcluster2"

## check if transfer is completed. 
DimPlot(B73vsBif3.individual.rmdead.int.subcluster2, reduction = "umap", label = TRUE, label.size = 10, pt.size = 1)

```



```{r}

# Display unique cluster labels
unique(Idents(B73vsBif3.individual.rmdead.int.subcluster2))


## change cluster labels for 6_0 and 6_1 to be 6 and 9 respectively.
## meanwhile, merge cell cycle cluster 7, 9, and 13 to be 7
## meanwhile, change cluster label 14 to be 13


new.cluster.ids <- c("15", "13", "0", "1", "7", "4", "6", "10", "14", "8", "5", "2", "11","12","9","3")

names(new.cluster.ids) <- levels(B73vsBif3.individual.rmdead.int.subcluster2)

B73vsBif3.individual.rmdead.int.subcluster2.rename <- RenameIdents(B73vsBif3.individual.rmdead.int.subcluster2, new.cluster.ids)

DimPlot(B73vsBif3.individual.rmdead.int.subcluster2.rename, reduction = "umap", label = TRUE, label.size = 8, pt.size = 1)


saveRDS(B73vsBif3.individual.rmdead.int.subcluster2.rename, file = "B73vsBif3.individual.rmdead.int.subcluster2.rename.rds")


```


```{r}
### identify DEG for specific clusters. 

B73vsBif3.individual.rmdead.int.subcluster2.forDEG <- B73vsBif3.individual.rmdead.int.subcluster2 ## assign to new object so it won't mess up the source labels. 


B73vsBif3.individual.rmdead.int.subcluster2.forDEG$celltype.source <- paste(B73vsBif3.individual.rmdead.int.subcluster2.forDEG$subcluster2, B73vsBif3.individual.rmdead.int.subcluster2.forDEG$source, sep = "_")

B73vsBif3.individual.rmdead.int.subcluster2.forDEG$celltype <- Idents(B73vsBif3.individual.rmdead.int.subcluster2.forDEG)

Idents(B73vsBif3.individual.rmdead.int.subcluster2.forDEG) <- "celltype.source"

## SPM Stem cell DEG

b.interferon.response <- FindMarkers(B73vsBif3.individual.rmdead.int.subcluster2.forDEG, ident.1 = "2_0_B73", ident.2 = "2_0_Bif3", verbose = FALSE)

write.csv(b.interferon.response, file = "Cluster2_0_SPM.stemcell_DEG_B73vsBif3.individual.rmdead.int.subcluster2.forDEG.csv")



## SPM Stem cell DEG--- nO default cutoff

b.interferon.response <- FindMarkers(B73vsBif3.individual.rmdead.int.subcluster2.forDEG, ident.1 = "2_0_B73", ident.2 = "2_0_Bif3", verbose = FALSE, logfc.threshold = 0, min.pct = 0, min.cells.feature = 1,   min.cells.group = 1)

write.csv(b.interferon.response, file = "B73-WT_vs_Bif3Bif3-mutant_cluster2_0.SPM.stemcell_Seurat-wilcox_NoDefault-cutoff.csv")




### IM Stem cell DEG

b.interferon.response <- FindMarkers(B73vsBif3.individual.rmdead.int.subcluster2.forDEG, ident.1 = "10_B73", ident.2 = "10_Bif3", verbose = FALSE)

write.csv(b.interferon.response, file = "Cluster10_IM.stemcell_DEG_B73vsBif3.individual.rmdead.int.subcluster2.forDEG.csv")





### IM Stem cell DEG-- No default cutoff

b.interferon.response <- FindMarkers(B73vsBif3.individual.rmdead.int.subcluster2.forDEG, ident.1 = "10_B73", ident.2 = "10_Bif3", verbose = FALSE, logfc.threshold = 0, min.pct = 0, min.cells.feature = 1,   min.cells.group = 1)

write.csv(b.interferon.response, file = "B73-WT_vs_Bif3Bif3-mutant_cluster10.IM.stemcell_Seurat-wilcox_NoDefault-cutoff.csv")





## in cluster 1 SPM stem cell
VlnPlot(B73vsBif3.individual.rmdead.int.subcluster2, features = c("GRMZM2G372364", "GRMZM2G059392", "GRMZM2G180190", "GRMZM2G171400", "GRMZM2G132623","GRMZM2G047448"), split.by = "source", idents = 2, pt.size = 0, group.by="subcluster2")

## in cluster 9 IM stem cell
VlnPlot(B73vsBif3.individual.rmdead.int.subcluster2, features = c("GRMZM2G372364", "GRMZM2G059392", "GRMZM2G180190", "GRMZM2G171400", "GRMZM2G132623","GRMZM2G047448"), split.by = "source", idents = 10, pt.size = 0, group.by="subcluster2")


```
